# Generated by Django 2.2.5 on 2019-09-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('username', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('mobileno', models.CharField(blank=True, max_length=250)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='logregister',
        ),
    ]
