# Generated by Django 2.2.2 on 2019-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
                ('passwords', models.CharField(max_length=250)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
