# Generated by Django 2.2.2 on 2019-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='passwords',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='pin',
        ),
    ]
