# Generated by Django 2.2.2 on 2019-08-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsletter',
            new_name='newsletters',
        ),
    ]
