# Generated by Django 2.2.2 on 2019-08-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190805_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact',
        ),
    ]
