# Generated by Django 2.2.2 on 2019-08-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190805_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='mobile',
        ),
    ]
