# Generated by Django 4.1.5 on 2023-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakerlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='image',
            field=models.ImageField(upload_to='speaker'),
        ),
    ]
