# Generated by Django 2.2.5 on 2019-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
